version: "3.8"
services:
  db:
    image: docker.io/postgres:latest
    container_name: cafe-postgres
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
      #Use this if you want only schema
      #- ./mini-project/week-6/data/init.sql:/docker-entrypoint-initdb.d/init.sql

      #Use this if you want schema with some data in DB
      - ./mini-project/week-6/data/cafe_dump.sql:/docker-entrypoint-initdb.d/cafe_dump.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: